name: CareMedia
favicon: null
layout_spectrum: 0.67628
typography_spectrum: 0.12640949757769704
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 1
  lightness: 0.03907234803773463
  saturation: 0.2155955561902374
  rhythmicContrast: 0.8857701339293271
purpose: []
